# Generated by Django 5.2 on 2025-05-12 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
